#!/usr/bin/env bash

# 16/03/2023
#Beñat Yañez
#Model a neutral population of Arabidopsis thaliana
#Parameters from Southern Sweden population Huber et al
#Need to run "sconda simulations"

# Grid Engine options (lines prefixed with #$)
#$ -N dem_model-AT                                                                      # Name of job in 'wstat' list
#$ -V                                                                                           # Pass current environment to job
#$ -cwd                                                                                         # Run file from current working directory
#$ -l h=c6
#$ -pe smp 10                                                                                   # Run array job on this sub-server
#$ -t 1-5
#$ -o /data/hartfield/atsweeps/scripts/output/          # Folder for STDOUT print
#$ -e /data/hartfield/atsweeps/scripts/error/           # Folder for STDERR print

chrmnm=${SGE_TASK_ID}
#Define the number of replicates
replicate=150
#Change number in {} to change the number of simulations
for (( n=1; n <= $replicate; ++n))
 do
  python simulation.py "$chrmnm" $n

# Copy file back to head folder
  rsync -avz /scratch/byanez/Vcf_Chr"$chrmnm"_Neutral_repeat"$n"_Real.vcf /data/hartfield/atsweeps/analyses/byanez/VCF

 python haploidconversion.py "$chrmnm" $n

  # Copy file back to head folder
 rsync -avz /scratch/byanez/Vcf_Chr"$chrmnm"_Neutral_Diploid_repeat"$n"_Real.vcf /data/hartfield/atsweeps/analyses/byanez/VCF
  done
  
